# Generated by Django 3.2 on 2021-04-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='user',
            new_name='owner',
        ),
    ]
