# Generated by Django 3.2 on 2021-04-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceType', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=400)),
                ('url', models.CharField(max_length=400)),
            ],
        ),
    ]
