# Generated by Django 3.2 on 2021-04-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
